"""Made order unnullable

Revision ID: 8234bc26d480
Revises: dad43fb621b4
Create Date: 2025-05-30 17:25:36.031859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8234bc26d480'
down_revision: Union[str, None] = 'dad43fb621b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('units', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('units', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
