"""Changed PromptLog model

Revision ID: 959604b5e91e
Revises: 741b6190caf5
Create Date: 2025-05-28 19:56:46.131987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '959604b5e91e'
down_revision: Union[str, None] = '741b6190caf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_logs', sa.Column('tokens_used', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('prompt_logs_unit_id_fkey'), 'prompt_logs', type_='foreignkey')
    op.drop_column('prompt_logs', 'type')
    op.drop_column('prompt_logs', 'unit_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_logs', sa.Column('unit_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('prompt_logs', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('prompt_logs_unit_id_fkey'), 'prompt_logs', 'units', ['unit_id'], ['id'])
    op.drop_column('prompt_logs', 'tokens_used')
    # ### end Alembic commands ###
